### PR TITLE
entrypoint.sh added.

### PR DESCRIPTION
**Pull request by ntalreja1**

### CODE REVIEW

**Comment by ntalreja1** [comment]
Entrypoint.sh code ok

**Comment by ntalreja1** [comment]
review done

**Comment by ntalreja1** [comment]
review done

**Comment by ntalreja1** [comment]
review done

**Review by ntalreja1 — COMMENTED** [review]
looks good

**Review by ntalreja1 — COMMENTED** [review]
looks good 2

**Review by ntalreja — COMMENTED** [review]
looks good

**Review by ntalreja1 — COMMENTED** [review]
good

**Review by ntalreja — APPROVED** [review]

**Pull request merged**
